config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events
  resources :users

  get "/attend/:id", to: "event_attendees#attend", as: "attend"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, dependent: :destroy

  validates :name, presence: true, length: { maximum: 150 }
  validates :time, presence: true

  scope :past, -> { where(time: ..Time.now) }
  scope :future, -> { where(time: Time.now..) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, class_name: "Event", foreign_key: "creator_id", inverse_of: :creator
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!, only: :attend
  def attend
    @event = Event.find_by(id: params[:id])
    @event.attendees << current_user
    redirect_to event_path(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [ :show, :index ]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      @event.attendees << current_user
      redirect_to current_user
    else
      render :new, status: 422
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def update
    @event = Event.find_by(id: params[:id])

    if @event.update(event_params)
      redirect_to current_user
    else
      render :edit, status: 422
    end
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    @event.destroy

    redirect_to current_user, status: 303
  end

  private

  def event_params
    params.require(:event).permit(:name, :time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Make the changes to your event</h1>
<%= render "shared/event_form", event: @event %>

app/views/events/index.html.erb
<h1>Private Events</h1>

<%if user_signed_in? %>
  <%= link_to 'Profile', user_path(current_user) %>
<% end %>

<h2>Future Events</h2>
<%= render "shared/event_list", events: @events.future %>

<% if user_signed_in? %>
  <%= button_to 'Log Out', destroy_user_session_path, method: :delete%>
<% else %>
  <%= link_to 'Log In', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/events/new.html.erb
<h1>What's the event, <%= current_user.name %>?</h1>

<%= render "shared/event_form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h4>Created by: <%= link_to "#{@event.creator.name}", user_path(@event.creator) %></h4>
<h3>Attendees:</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= link_to "Home", root_path %>
    <%= link_to 'Create Event', new_event_path %> <br><br>
  </body>
</html>

app/views/shared/_event_form.html.erb
<%= form_with model: event do |form| %>
  <div>
    <%= form.label :name, 'Event name: ' %>
    <%= form.text_field :name, autofocus: true %>
  </div><br>
  <div>
    <%= form.label :time, 'Date and time: ' %>
    <%= form.datetime_local_field :time %>
  </div><br>
  <%= form.submit %>
<% end %>

app/views/shared/_event_list.html.erb
<ol>
  <% events.each do |event| %>
    <li>
      <ul>
        <li>
          Event name: <%= event.name %>
        </li>
        <li>
          Date and time: <%= event.time.strftime("%d/%m/%Y %I:%M %p") %>
        </li>
        <% unless current_user == event.creator %>
        <li>
          Organised by: <%= link_to "#{event.creator.name}", user_path(event.creator) %>
        </li>
        <% end %>
        <% if event.attendees.include?(current_user) %>
          <li>You're going!</li>
        <% else %>
          <li><%= link_to "Attend", attend_path(event) %></li>
        <% end %>
        <li>
          <%= link_to "See who attends?", event_path(event) %>
        </li>
        <% if current_user == event.creator && event.time > Time.now %>
          <li>
            <%= link_to "Edit", edit_event_path(event) %>
          </li>
          <li>
            <%= link_to "Delete", event_path(event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>

app/views/users/show.html.erb
<h1>
  <% if current_user == @user %>
    Your
  <% else %>
    <%= @user.name %>
  <% end %>
  private events
</h1>
<h3>Hello <%= @user.name %>!</h3>
<h2>Events created</h2>
<h3>Past events</h3>
<%= render "shared/event_list", events: @user.created_events.past %>
<h3>Future events</h3>
<%= render "shared/event_list", events: @user.created_events.future %>
<% if current_user == @user %>
  <h3>Events attended</h3>
  <%= render "shared/event_list", events: @user.attended_events.past %>
  <h3>Events attending</h3>
  <%= render "shared/event_list", events: @user.attended_events.future %>
<% end %>